<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Edition;
use App\Models\EditionContribution;
use App\Models\EditionTransaction;
use App\Models\GameMatch;
use App\Models\PlayerRegistration;
use App\Services\Finance\ContributorRankingService;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Read-side navigation/reporting hub only (Phase 3.43) — every export/
 * PDF it links to is generated by its own existing controller
 * (PlayerRegistrationController::export(), EditionTransactionController::export(),
 * EditionContributionController::export(), EditionController::reportPdf(),
 * Public\MatchController::scorecardPdf()); this controller never
 * re-implements any of them. The one genuinely new report is the
 * Financial Summary, which itself only reads existing aggregates
 * (EditionTransaction::summaryForEdition(), the same grouped
 * registration query the dashboard uses, and ContributorRankingService).
 *
 * Admin-only throughout: every report here either contains financial
 * data or links to an admin-only resource, so gating the whole hub
 * behind the existing "manage-tournament" Gate (the same broad-area
 * check EditionPolicy/EditionTransactionPolicy/etc. already enforce
 * per-resource) is the simplest correct V1, per this phase's own
 * explicit instruction not to invent a weaker scorer-facing subset.
 */
class ReportsController extends Controller
{
    public function __construct(private readonly ContributorRankingService $contributorRanking) {}

    public function index(Request $request): View
    {
        $this->authorize('manage-tournament');

        $edition = $this->resolveEdition($request);

        $recentMatches = $edition
            ? GameMatch::query()
                ->where('edition_id', $edition->id)
                ->where('match_status', 'completed')
                ->with(['teamA.team', 'teamB.team'])
                ->orderByDesc('scheduled_at')
                ->limit(10)
                ->get()
            : collect();

        return view('admin.reports.index', [
            'edition' => $edition,
            'editions' => Edition::orderByDesc('year')->get(['id', 'name']),
            'recentMatches' => $recentMatches,
        ]);
    }

    /**
     * The one genuinely new report this phase adds — a print-friendly
     * HTML page (no PDF: nothing in the existing project makes a PDF a
     * trivial wrapper here the way the contribution receipt's shared
     * Blade template does, so a second rendering pipeline isn't worth
     * it for a V1 summary). Every figure is read from the exact same
     * aggregates the Dashboard already uses — never recalculated with
     * different semantics.
     */
    public function financialSummary(Request $request): View
    {
        $this->authorize('manage-tournament');

        $edition = $this->resolveEdition($request);

        $registrationStats = collect();
        $financeSummary = ['income' => 0.0, 'expense' => 0.0, 'balance' => 0.0];
        $contributionCount = 0;
        $contributionTotal = 0.0;
        $recognizedContributorsCount = 0;

        if ($edition) {
            // Same grouped query shape as DashboardController — counts
            // and the paid fee total from each row's own stored value,
            // never edition->registration_fee x count.
            $registrationStats = PlayerRegistration::query()
                ->where('edition_id', $edition->id)
                ->selectRaw('payment_status, count(*) as total, COALESCE(SUM(registration_fee), 0) as fee_total')
                ->groupBy('payment_status')
                ->get()
                ->keyBy('payment_status');

            $financeSummary = EditionTransaction::summaryForEdition($edition->id);

            $contributionStats = EditionContribution::query()
                ->where('edition_id', $edition->id)
                ->selectRaw('count(*) as total, COALESCE(SUM(amount), 0) as amount_total')
                ->first();
            $contributionCount = (int) $contributionStats->total;
            $contributionTotal = (float) $contributionStats->amount_total;

            $recognizedContributorsCount = count($this->contributorRanking->getEditionRanking($edition));
        }

        return view('admin.reports.financial-summary', [
            'edition' => $edition,
            'generatedAt' => now(),
            'paidRegistrations' => (int) ($registrationStats->get('paid')->total ?? 0),
            'paidRegistrationAmount' => (float) ($registrationStats->get('paid')->fee_total ?? 0),
            'pendingRegistrations' => (int) ($registrationStats->get('pending')->total ?? 0),
            'failedRegistrations' => (int) ($registrationStats->get('failed')->total ?? 0),
            'refundedRegistrations' => (int) ($registrationStats->get('refunded')->total ?? 0),
            'financeSummary' => $financeSummary,
            'contributionCount' => $contributionCount,
            'contributionTotal' => $contributionTotal,
            'recognizedContributorsCount' => $recognizedContributorsCount,
        ]);
    }

    /**
     * Explicit edition_id resolves that specific edition when it
     * exists; an invalid/unknown id safely falls back to the default
     * rather than erroring, since this is a navigational selector, not
     * a resource route. With no edition_id at all, uses the exact same
     * active -> soonest upcoming -> most recent completed rule as
     * DashboardController::currentEdition() — duplicated locally for
     * the same reason that method's own docblock gives (three lines,
     * not worth coupling two controllers over).
     */
    private function resolveEdition(Request $request): ?Edition
    {
        if ($editionId = $request->integer('edition_id')) {
            $edition = Edition::find($editionId);

            if ($edition) {
                return $edition;
            }
        }

        return Edition::where('status', 'active')->latest('year')->first()
            ?? Edition::where('status', 'upcoming')->orderBy('year')->first()
            ?? Edition::where('status', 'completed')->latest('year')->first();
    }
}
